version: "3.9"
services:

  api:
    container_name: test-mm
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/test-mm
      - /home/test-mm/node_modules
  mongodb:
    container_name: test-mm-db
    image: mongo:5.0
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ~/test-mm/mongo:/data/db
    command: [--auth]
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
